name: Build Python Executable

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirement.txt

    - name: Build with PyInstaller
      run: pyinstaller --onefile --name "PCDdebugger-${{ matrix.os }}" PCDdebugger.py # <--- Name changed here

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: PCDdebugger-${{ matrix.os }} # <--- And changed here for the artifact name
        path: dist/
